<?php

/**
 * @file
 * Contains tgb_news.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function tgb_news_help($route_name, RouteMatchInterface $route_match)
{
    switch ($route_name) {
        // Main module help for the tgb_news module.
        case 'help.page.tgb_news':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('TGB Modules for content type &quot;News&quot; &amp; views') . '</p>';
            return $output;

        default:
    }
}

/**
 * Implements hook_theme().
 */
function tgb_news_theme()
{
    return [
        'tgb_news' => [
            'render element' => 'children',
        ],
        'views_view__actualites__liste' => [
            'template' => 'views-view--actualites--liste',
            'base hook' => 'views_view',
        ],
        'views_view__actualites__bloc' => [
            'template' => 'views-view--actualites--bloc',
            'base hook' => 'views_view',
        ],
        'views_view__actualites__relation' => [
            'template' => 'views-view--actualites--relation',
            'base hook' => 'views_view',
        ],
        'views_view_unformatted__actualites__liste' => [
            'template' => 'views-view-unformatted--actualites--liste',
            'base hook' => 'views_view_unformatted',
        ],
        'views_view_unformatted__actualites__bloc' => [
            'template' => 'views-view-unformatted--actualites--bloc',
            'base hook' => 'views_view_unformatted',
        ],
        'views_view_unformatted__actualites__relation' => [
            'template' => 'views-view-unformatted--actualites--relation',
            'base hook' => 'views_view_unformatted',
        ],
        'node__actualite__teaser' => [
            'template' => 'node--actualite--teaser',
            'base hook' => 'node',
        ],
        'node__actualite__full' => [
            'template' => 'node--actualite--full',
            'base hook' => 'node',
        ],
    ];
}
